"""
SQLAlchemy models — the complete schema as Python code.

Tables:
  messages         — persisted message history (written by Kafka consumer)
  channels         — channel metadata (name, creator, soft-delete)
  channel_members  — membership edges (who belongs to which channel)

Why SQLAlchemy models instead of raw SQL?
  1. Alembic reads these models and auto-generates migrations
     by comparing them to the current DB state.
  2. Single source of truth — the schema lives in code.
  3. Type safety — your IDE knows message.channel_id is a string.

We use SQLAlchemy 2.0 declarative style (mapped_column).
"""

from datetime import datetime
from sqlalchemy import (
    String,
    Text,
    Boolean,
    DateTime,
    Index,
    CheckConstraint,
    func,
)
from sqlalchemy.orm import (
    DeclarativeBase,
    Mapped,
    mapped_column,
)


class Base(DeclarativeBase):
    """Base class for all models. Alembic uses this to
    discover tables and generate migrations."""
    pass


# ── Valid membership roles ────────────────────────────────────
# Enforced at the service layer + CHECK constraint in DB.
# Not a Postgres ENUM — those are painful to migrate.
VALID_ROLES = {"owner", "admin", "member"}


# ─────────────────────────────────────────────────────────────
# Messages (unchanged from your existing model)
# ─────────────────────────────────────────────────────────────

class Message(Base):
    __tablename__ = "messages"

    # ── Core fields ───────────────────────────────────────────
    message_id: Mapped[str] = mapped_column(
        String(128), primary_key=True,
        comment="UUID generated by ingest service. PK = free dedup.",
    )
    channel_id: Mapped[str] = mapped_column(
        String(128), nullable=False, index=True,
        comment="Target channel. No FK — decoupled from channels table "
                "so Kafka consumer doesn't need channel to exist at write time.",
    )
    sender_id: Mapped[str] = mapped_column(
        String(128), nullable=False,
        comment="From authenticated connection, not payload.",
    )
    content: Mapped[str] = mapped_column(
        Text, nullable=False,
        comment="Message body (max 4096 chars enforced at ingest).",
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False,
        comment="When the message was sent.",
    )

    # ── Tracing / debugging ───────────────────────────────────
    correlation_id: Mapped[str | None] = mapped_column(
        String(128), nullable=True,
        comment="Trace ID for the full pipeline.",
    )
    client_request_id: Mapped[str | None] = mapped_column(
        String(128), nullable=True,
        comment="Client-generated idempotency key.",
    )

    # ── Metadata ──────────────────────────────────────────────
    persisted_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
        comment="When this row was written to DB.",
    )

    __table_args__ = (
        Index(
            "idx_messages_channel_time",
            "channel_id",
            created_at.desc(),
        ),
        Index(
            "idx_messages_sender_time",
            "sender_id",
            created_at.desc(),
        ),
        Index(
            "idx_messages_persisted",
            persisted_at.desc(),
        ),
    )

    def __repr__(self) -> str:
        return (
            f"<Message id={self.message_id[:8]}... "
            f"channel={self.channel_id} "
            f"sender={self.sender_id}>"
        )


# ─────────────────────────────────────────────────────────────
# Channels
# ─────────────────────────────────────────────────────────────

class Channel(Base):
    """
    Channel metadata.

    Soft-delete design:
      Hard-deleting a channel while messages reference it either
      requires CASCADE (data loss) or leaves orphan messages.
      Soft-delete lets us hide channels immediately, keep message
      history for compliance, and purge on our own schedule.
    """
    __tablename__ = "channels"

    channel_id: Mapped[str] = mapped_column(
        String(128),
        primary_key=True,
        comment="UUID generated at creation time.",
    )
    name: Mapped[str] = mapped_column(
        String(256),
        nullable=False,
        comment="Human-readable name. Not unique — multiple "
                "teams can have a #general.",
    )
    description: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
        comment="Optional long-form description.",
    )
    created_by: Mapped[str] = mapped_column(
        String(128),
        nullable=False,
        comment="user_id of the creator.",
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )

    # ── Soft-delete ───────────────────────────────────────────
    is_deleted: Mapped[bool] = mapped_column(
        Boolean,
        default=False,
        server_default="false",
        nullable=False,
    )
    deleted_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
    )

    __table_args__ = (
        # Partial index: only non-deleted channels. Keeps the
        # index small even with millions of archived channels.
        Index(
            "idx_channels_active",
            "is_deleted",
            created_at.desc(),
            postgresql_where=(is_deleted == False),  # noqa: E712
        ),
        Index(
            "idx_channels_created_by",
            "created_by",
            created_at.desc(),
        ),
    )

    def __repr__(self) -> str:
        return f"<Channel id={self.channel_id[:8]}... name={self.name!r}>"


# ─────────────────────────────────────────────────────────────
# Channel Members
# ─────────────────────────────────────────────────────────────

class ChannelMember(Base):
    """
    Join table: which users belong to which channels.

    Composite PK (channel_id, user_id):
      - Enforces uniqueness (can't join twice) for free
      - Is the exact index shape for "is user X in channel Y?"
      - Avoids a useless surrogate id column

    This replaces the raw-SQL channel_members table referenced
    in ChannelMembershipService. Column names are identical so
    the service's existing SQL queries continue to work.
    """
    __tablename__ = "channel_members"

    channel_id: Mapped[str] = mapped_column(
        String(128),
        primary_key=True,
    )
    user_id: Mapped[str] = mapped_column(
        String(128),
        primary_key=True,
    )
    role: Mapped[str] = mapped_column(
        String(32),
        nullable=False,
        default="member",
        server_default="member",
        comment="One of: owner, admin, member.",
    )
    joined_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )

    __table_args__ = (
        # Reverse lookup: "what channels does user X belong to?"
        # The PK index is (channel_id, user_id) — wrong column
        # order for user-first queries.
        Index(
            "idx_channel_members_user",
            "user_id",
        ),
        # DB-level role validation — belt-and-suspenders
        # alongside the app-layer check.
        CheckConstraint(
            "role IN ('owner', 'admin', 'member')",
            name="ck_channel_members_role",
        ),
    )

    def __repr__(self) -> str:
        return (
            f"<ChannelMember channel={self.channel_id[:8]}... "
            f"user={self.user_id[:8]}... role={self.role}>"
        )