"""
SQLAlchemy models — the schema as Python code.

Why SQLAlchemy models instead of raw SQL?
  1. Alembic reads these models and auto-generates migrations
     by comparing them to the current DB state. Change a
     column here → alembic revision --autogenerate → done.
  2. Single source of truth. The schema lives in code, not
     in a SQL file that drifts from reality.
  3. Type safety. Your IDE knows message.channel_id is a
     string, not an int.

We use SQLAlchemy 2.0 declarative style (mapped_column)
instead of the old Column() style. Cleaner, better typing.
"""

from datetime import datetime, timezone
from sqlalchemy import (
    String,
    Text,
    DateTime,
    Index,
    func,
)
from sqlalchemy.orm import (
    DeclarativeBase,
    Mapped,
    mapped_column,
)


class Base(DeclarativeBase):
    """Base class for all models. Alembic uses this to
    discover tables and generate migrations."""
    pass


class Message(Base):
    __tablename__ = "messages"

    # ── Core fields ───────────────────────────────────────────
    message_id: Mapped[str] = mapped_column(
        String(128), primary_key=True,
        comment="UUID generated by ingest service. PK = free dedup via ON CONFLICT.",
    )
    channel_id: Mapped[str] = mapped_column(
        String(128), nullable=False, index=True,
        comment="Target channel",
    )
    sender_id: Mapped[str] = mapped_column(
        String(128), nullable=False,
        comment="From authenticated connection, not payload",
    )
    content: Mapped[str] = mapped_column(
        Text, nullable=False,
        comment="Message body (max 4096 chars enforced at ingest)",
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False,
        comment="When the message was sent (from client timestamp)",
    )

    # ── Tracing / debugging ───────────────────────────────────
    correlation_id: Mapped[str | None] = mapped_column(
        String(128), nullable=True,
        comment="Trace ID for the full pipeline",
    )
    client_request_id: Mapped[str | None] = mapped_column(
        String(128), nullable=True,
        comment="Client-generated idempotency key",
    )

    # ── Metadata ──────────────────────────────────────────────
    persisted_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
        comment="When this row was written to DB (not when message was sent)",
    )

    # ── Indexes ───────────────────────────────────────────────
    # Defined here so Alembic picks them up automatically.
    __table_args__ = (
        # Primary query: channel history with pagination
        # SELECT * FROM messages WHERE channel_id = ? ORDER BY created_at DESC LIMIT 50
        Index(
            "idx_messages_channel_time",
            "channel_id",
            created_at.desc(),
        ),
        # User's message history
        Index(
            "idx_messages_sender_time",
            "sender_id",
            created_at.desc(),
        ),
        # Recently persisted (monitoring)
        Index(
            "idx_messages_persisted",
            persisted_at.desc(),
        ),
    )

    def __repr__(self) -> str:
        return (
            f"<Message id={self.message_id[:8]}... "
            f"channel={self.channel_id} "
            f"sender={self.sender_id}>"
        )