"""add users and refresh tokens

Revision ID: af16df0e9d19
Revises: fd0b3ac038d3
Create Date: 2026-04-06 15:26:15.651416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'af16df0e9d19'
down_revision: Union[str, Sequence[str], None] = 'fd0b3ac038d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel_members',
    sa.Column('channel_id', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=32), server_default='member', nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('owner', 'admin', 'member')", name='ck_channel_members_role'),
    sa.PrimaryKeyConstraint('channel_id', 'user_id')
    )
    op.create_index('idx_channel_members_user', 'channel_members', ['user_id'], unique=False)
    op.create_table('channels',
    sa.Column('channel_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('channel_id')
    )
    op.create_index('idx_channels_active', 'channels', ['is_deleted', sa.literal_column('created_at DESC')], unique=False, postgresql_where=sa.text('is_deleted = false'))
    op.create_index('idx_channels_created_by', 'channels', ['created_by', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('token_id', sa.String(length=128), nullable=False, comment='UUID — the token itself is a separate opaque string.'),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('token_hash', sa.String(length=256), nullable=False, comment='SHA-256 of the actual token value. We never store the raw token — same principle as passwords.'),
    sa.Column('device_id', sa.String(length=256), nullable=True, comment='Client-provided device identifier.'),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('is_revoked', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('family_id', sa.String(length=128), nullable=False, comment='All tokens in a rotation chain share a family_id. If a revoked token is reused, we revoke the entire family — signals token theft.'),
    sa.PrimaryKeyConstraint('token_id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('idx_refresh_tokens_expires', 'refresh_tokens', ['expires_at'], unique=False)
    op.create_index('idx_refresh_tokens_hash', 'refresh_tokens', ['token_hash'], unique=False)
    op.create_index('idx_refresh_tokens_user_active', 'refresh_tokens', ['user_id', 'is_revoked'], unique=False, postgresql_where=sa.text('is_revoked = false'))
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.String(length=128), nullable=False, comment='UUID generated at registration.'),
    sa.Column('email', sa.String(length=320), nullable=False, comment='RFC 5321 max email length is 320 chars.'),
    sa.Column('display_name', sa.String(length=256), nullable=False, comment='Shown to other users. Not unique.'),
    sa.Column('password_hash', sa.String(length=256), nullable=True, comment='bcrypt hash. Null for OAuth-only accounts.'),
    sa.Column('oauth_provider', sa.String(length=64), nullable=True, comment="'google' or 'github'. Null for password-only."),
    sa.Column('oauth_provider_id', sa.String(length=256), nullable=True, comment="The user's ID from the OAuth provider."),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True, comment='Updated on each successful login.'),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_index('idx_users_oauth', 'users', ['oauth_provider', 'oauth_provider_id'], unique=True, postgresql_where=sa.text('oauth_provider IS NOT NULL'))
    op.alter_column('messages', 'message_id',
               existing_type=sa.VARCHAR(length=128),
               comment=None,
               existing_comment='UUID generated by ingest service. PK = free dedup via ON CONFLICT.',
               existing_nullable=False)
    op.alter_column('messages', 'channel_id',
               existing_type=sa.VARCHAR(length=128),
               comment=None,
               existing_comment='Target channel',
               existing_nullable=False)
    op.alter_column('messages', 'sender_id',
               existing_type=sa.VARCHAR(length=128),
               comment=None,
               existing_comment='From authenticated connection, not payload',
               existing_nullable=False)
    op.alter_column('messages', 'content',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Message body (max 4096 chars enforced at ingest)',
               existing_nullable=False)
    op.alter_column('messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='When the message was sent (from client timestamp)',
               existing_nullable=False)
    op.alter_column('messages', 'correlation_id',
               existing_type=sa.VARCHAR(length=128),
               comment=None,
               existing_comment='Trace ID for the full pipeline',
               existing_nullable=True)
    op.alter_column('messages', 'client_request_id',
               existing_type=sa.VARCHAR(length=128),
               comment=None,
               existing_comment='Client-generated idempotency key',
               existing_nullable=True)
    op.alter_column('messages', 'persisted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='When this row was written to DB (not when message was sent)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'persisted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When this row was written to DB (not when message was sent)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('messages', 'client_request_id',
               existing_type=sa.VARCHAR(length=128),
               comment='Client-generated idempotency key',
               existing_nullable=True)
    op.alter_column('messages', 'correlation_id',
               existing_type=sa.VARCHAR(length=128),
               comment='Trace ID for the full pipeline',
               existing_nullable=True)
    op.alter_column('messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When the message was sent (from client timestamp)',
               existing_nullable=False)
    op.alter_column('messages', 'content',
               existing_type=sa.TEXT(),
               comment='Message body (max 4096 chars enforced at ingest)',
               existing_nullable=False)
    op.alter_column('messages', 'sender_id',
               existing_type=sa.VARCHAR(length=128),
               comment='From authenticated connection, not payload',
               existing_nullable=False)
    op.alter_column('messages', 'channel_id',
               existing_type=sa.VARCHAR(length=128),
               comment='Target channel',
               existing_nullable=False)
    op.alter_column('messages', 'message_id',
               existing_type=sa.VARCHAR(length=128),
               comment='UUID generated by ingest service. PK = free dedup via ON CONFLICT.',
               existing_nullable=False)
    op.drop_index('idx_users_oauth', table_name='users', postgresql_where=sa.text('oauth_provider IS NOT NULL'))
    op.drop_index('idx_users_email', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index('idx_refresh_tokens_user_active', table_name='refresh_tokens', postgresql_where=sa.text('is_revoked = false'))
    op.drop_index('idx_refresh_tokens_hash', table_name='refresh_tokens')
    op.drop_index('idx_refresh_tokens_expires', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('idx_channels_created_by', table_name='channels')
    op.drop_index('idx_channels_active', table_name='channels', postgresql_where=sa.text('is_deleted = false'))
    op.drop_table('channels')
    op.drop_index('idx_channel_members_user', table_name='channel_members')
    op.drop_table('channel_members')
    # ### end Alembic commands ###
