"""initial migration

Revision ID: fd0b3ac038d3
Revises: 
Create Date: 2026-04-02 11:19:14.107542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd0b3ac038d3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('message_id', sa.String(length=128), nullable=False, comment='UUID generated by ingest service. PK = free dedup via ON CONFLICT.'),
    sa.Column('channel_id', sa.String(length=128), nullable=False, comment='Target channel'),
    sa.Column('sender_id', sa.String(length=128), nullable=False, comment='From authenticated connection, not payload'),
    sa.Column('content', sa.Text(), nullable=False, comment='Message body (max 4096 chars enforced at ingest)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='When the message was sent (from client timestamp)'),
    sa.Column('correlation_id', sa.String(length=128), nullable=True, comment='Trace ID for the full pipeline'),
    sa.Column('client_request_id', sa.String(length=128), nullable=True, comment='Client-generated idempotency key'),
    sa.Column('persisted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='When this row was written to DB (not when message was sent)'),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_index('idx_messages_channel_time', 'messages', ['channel_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_messages_persisted', 'messages', [sa.literal_column('persisted_at DESC')], unique=False)
    op.create_index('idx_messages_sender_time', 'messages', ['sender_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('ix_messages_channel_id'), 'messages', ['channel_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_channel_id'), table_name='messages')
    op.drop_index('idx_messages_sender_time', table_name='messages')
    op.drop_index('idx_messages_persisted', table_name='messages')
    op.drop_index('idx_messages_channel_time', table_name='messages')
    op.drop_table('messages')
    # ### end Alembic commands ###
